language: node_js

node_js:
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"

git:
  depth: 1

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.npm
    - node_modules

matrix:
  fast_finish: true

before_script:
  - node --version
  - npm --version

script:
  - npm test

after_script:
  - npm run cover
